### ISSUE TITLE
Stashed-1.2.1.msi flagged as untrusted by Edge MS browser

### ISSUE THREAD

**Issue by serge-nikulin** [playscale/stashed.io#3] opened 2017-10-12 20:33 UTC
See the attached screenshot below.
Environment: Windows 10 with all updates installed:
```
Microsoft Windows [Version 10.0.15063]
```
![capture1](https://user-images.githubusercontent.com/31498077/31517738-bc536960-af51-11e7-8c5b-7d2121d34205.PNG)

**Comment by jsmouret** [comment] 2017-10-13 01:04
I double checked, this package is properly signed using "DigiCert EV Code Signing CA", which should prevent those kind of messages.
Do you see a SmartScreen popup when running the file?

**Comment by jsmouret** [comment] 2017-10-13 01:07
I tried directly from github releases or through https://stashed.io/download (which is just a redirect), and both seem to download properly with Edge.

![image](https://user-images.githubusercontent.com/2038285/31525872-e28112aa-aff5-11e7-9117-3368861e8e60.png)

**Comment by serge-nikulin** [comment] 2017-10-13 01:12
No, I did not see SmartScreen popup.
Actually, it happened on Monday(?) when I have updated the program.
The file originated from Amazon cloud.

**Comment by jsmouret** [comment] 2017-10-13 01:17
Github stores the releases on Amazon cloud, so that's normal.
Is it happening from home or the office?
(It could be that your office has very strict rules)

**Comment by serge-nikulin** [comment] 2017-10-13 01:19
It happened on a formally home-configured PC (our startup does not have an MS domain yet).
I am a sole admin on my PC and it does not have any GPs.

**Comment by jsmouret** [comment] 2017-10-13 01:22
I'm running out of ideas.
Let's keep the issue open and see if that happens again the next release.
Thanks for the feedback

**Comment by serge-nikulin** [comment] 2017-10-13 17:50
Yesterday I could not reproduce the issue but today I can.

1. Start Edge browser
1. Navigate to [https://stashed.io/home](https://stashed.io/home)
1. click Download button
1. Answer "Save" to Edge's question about "Run/Save?"
1. Edge says "running security scan..."
1. Edge shows the warning (see the screenshot).
![capture](https://user-images.githubusercontent.com/31498077/31558599-74dfdce2-b002-11e7-87ed-ae4654d3014b.PNG)

Part of the URL (I don't know how to extract full URLs from Edge):  
![capture1](https://user-images.githubusercontent.com/31498077/31558866-6cf1e52e-b003-11e7-8bc1-4ed076f1f151.PNG)

SHA256: ```deada5c72549300ce2e1976d32788036e74a832145021a83069e1e112fca2d27```
SHA1: ```17B82610E63F079798D1E8F814C12C813B27EE2A```
MD5:  ```D6B80F932985D9DD4D68860CD91FBA6D```

Please confirm the sums (at least any two).

Thanks!

**Comment by jsmouret** [comment] 2017-10-14 08:41
The sums are correct:
![image](https://user-images.githubusercontent.com/2038285/31574255-2ac99be6-b0fe-11e7-9458-6cbf3fa35041.png)

In theory, the package is signed with an EV certificate which prevents those kind of messages.
We will follow up with our provider (Digicert) to understand why it still randomly show this message.

**Comment by Justin-Randall** [comment] 2017-10-30 06:38
We contacted our certificate provider who verified that the installer is signed properly and the timestamp is correct. The dialog from Edge shows a "reputation" problem from Microsoft. The support team at DigiCert attempted to reproduce this problem on several machines (all running Edge) and could not reproduce it.

This appears to be an isolated incident, perhaps having something to do with the machine that was used. 

Without a way to reproduce it, and no other indications that there is a problem with the installer, I am going to close the issue for now. If any more info turns up, it would be handy to have it just in case another situation like this arises again.

Best regards.

**Closed by Justin-Randall** 2017-10-30 06:38 UTC
